### ISSUE TITLE
[Bug] Cannot open a specific instance anymore

### ISSUE THREAD

**Issue by Hunam6** [gorilla-devs/GDLauncher-Next-Issues#27]
**Operating System used:**

Windows 10 pro 64 bit

**Actual behavior:**

I can open all instances except one.

**Steps to reproduce the behavior:**

I've done nothing special, I think, the only thing is that I was installing Warfare the first time I tried to open an instance, and now, I've relaunched my launcher, I can no longer open an instance.

**Expected behavior:**

Open the instance.

**If applicable, add screenshots/videos to help explain:**

https://dabon.me/sbWEN5n7.mkv

**Comment by killpowa** [comment]
Could you send the logs?

**Comment by Hunam6** [comment]
Where are they?

**Comment by killpowa** [comment]
In the console. Just run the instance, then open the console in the top left corner and go to `console`

**Comment by Hunam6** [comment]
`Uncaught (in promise) Error: ENOENT: no such file or directory, open 'D:\Fichiers\Minecraft\gdlauncher_next\datastore\libraries\net\minecraft\1.15.2.json'`
