### ISSUE TITLE
[Bug] When GDlauncher is open F5 in browser refreshes GDlauncher in background

### ISSUE THREAD

**Issue by jinkhya** [gorilla-devs/GDLauncher-Next-Issues#40]
**Operating System used:**
Manjaro 5.6.2-1

**Actual behavior:**
Kinda a funny issue ; it took me days to figure out why I couldn't refresh firefox anymore or even use my F5 skill in some MMO I play. It turns out to be because GDlauncher is open in the background. No matter where I put GDlauncher, F5 refreshes it instead of the app above it.

**Steps to reproduce the behavior:**
- Open GDlauncher
- Open firefox and put it above GDlauncher
- Press F5 to refresh the tab of firefox.

**Expected behavior:**
F5 not bound to GDlauncher when not on top. 

**If applicable, add screenshots/videos to help explain:**
https://streamable.com/4oy8kb
In this video I press the F5 4 times and none of them refreshes firefox.

**Additional context:**

**Comment by TOLoneWolf** [comment]
Duplicate of #18

**Comment by jinkhya** [comment]
My bad, I checked in discord issues channel if this was reported and not here - rookie mistake. I'll close it, no need for 2 threads :)
Sorry about that.
