### ISSUE TITLE
[Feature] Ram amount per pack

### ISSUE THREAD

**Issue by aolsen96** [gorilla-devs/GDLauncher-Next-Issues#41]
**Describe the feature you would like to see added:**

The possibility to set ram allowed based on the instance you are lunching

**Comment by Daktyl198** [comment]
As far as I'm aware, this should already exist. Right click on an instance and select "Manage", on the first screen that pops up should be a check box for "Java Memory". Tick that and you should be able to change how much RAM is allocated when launching that pack.

Whether or not it's actually implemented, I haven't tested, but the feature is there in the UI.
